swagger: "2.0"
info:
  description: This is the API for the dungeon
  version: "1.0.0"
  title: Dungeon API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /view:
    get:
      operationId: "endpoint.get_view"
      summary: "Get everything in the room."
      description: "Currently returns everything in the room."
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              steps:
                type: integer
              score:
                type: integer
              things:
                type: array
                items:
                  properties:
                    x: 
                      type: integer
                    y: 
                      type: integer
                    looks_like: 
                      type: string
  /step:
    post:
      operationId: "endpoint.step"
      summary: "Step world forward."
      description: "Moves all agents."
      responses:
        201:
          description: "Stepped"
  /reset:
    put:
      operationId: "endpoint.reset"
      summary: "Clear all state."
      description: "Reinitialize the room."
      responses:
        200:
          description: "Successful operation"