swagger: "2.0"
info:
  description: This is the API for the dungeon
  version: "1.0.0"
  title: Dungeon API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

paths:
  /view:
    get:
      operationId: "endpoint.get_view"
      summary: "Get everything in the room."
      description: "Currently returns everything in the room."
      responses:
        200:
          description: "Successful operation"
          schema:
            type: array
            items:
              properties:
                x: 
                  type: integer
                y: 
                  type: integer
                looks_like: 
                  type: string
                id:
                  type: string
  /score:
    get:
      operationId: "endpoint.get_score"
      summary: "Get score."
      description: "Get score for some or all agents."
      parameters:
        - name: agent
          in: query
          required: false
          type: string
      responses:
        200:
          description: "Successful operation"
          schema:
            type: array
            items:
              properties:
                id: 
                  type: string
                score: 
                  type: integer
  /step:
    post:
      operationId: "endpoint.step"
      summary: "Step world forward."
      description: "Moves all agents."
      responses:
        201:
          description: "Stepped"
    get:
      operationId: "endpoint.get_steps"
      summary: "Get steps."
      description: "Get number of steps since beginning."
      responses:
        200:
          description: "Successful operation"
          schema:
            type: integer
  /reset:
    put:
      operationId: "endpoint.reset"
      summary: "Clear all state."
      description: "Reinitialize the room."
      responses:
        200:
          description: "Successful operation"